stages:
  - playerBuild

variables:
  OUTPUT_DIR: "build"    
  BUILD_PREFIX: "demo"
  UNITY_VERSION: "2019.4.9f1"
  UNITY_CACHE_SERVER: "localhost:8126"

default:
  before_script:
    - npm i

cache:
  paths:
    - node_modules/


production:Win64:
  stage: playerBuild
  when: always
  only:    
    - tags
  tags:    
    - windows
    - unity
  cache:
    key: windows
    paths:
      - Library/
  artifacts:
    name: production-windows-build
    expire_in: 2 hrs
    when: on_success
    paths:    
        - build/**
  variables:
    BUILD_TARGET: "StandaloneWindows64"
    BACKEND_BASE_URL: "https://production.mydomain.com/mygame" 
  script:
    - npx gulp buildWindows

develop:Win64:
  stage: playerBuild
  when: manual
  only:    
    - pushes
  tags:    
    - windows
    - unity
  cache:
    key: windows
    paths:
      - Library/
  artifacts:
    name: develop-windows-build
    expire_in: 2 hrs
    when: on_success
    paths:    
        - build/**
  variables:
    BUILD_TARGET: "StandaloneWindows64"
    BACKEND_BASE_URL: "https://develop.mydomain.com/mygame" 
  script:
    - npx gulp buildWindows