stages:
- build_demo_apk

build_apk:
  stage: "build_demo_apk"
  tags:
    - windows_x64
  script:
    - '"C:\Program Files\Unity2019.4\Editor\xUnity.exe"'
  artifacts:
    paths:
      - NuitrackDemo.apk
    expire_in: 14d