stages:
- build_package_and_NuitrackDemo

build_unity_package:
  stage: "build_package_and_NuitrackDemo"
  tags:
    - w10vbox
  script:
    - cmd /c echo %cd%
    - dir
    - dir "c:\"
    - dir "c:\Program Files"
    - cat test.sh
    - chmod +x ./test.sh
    - chmod +x ./deploy.sh
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
    expire_in: 14d