stages:
- build_demo_apk

build_apk:
  stage: "build_demo_apk"
  tags:
    - windows_x64
  script:
    - '"C:\Program Files\Unity2019.4\Editor\Unity.exe" -quit -logFile %cd%/build_log.txt -projectPath %cd% -executeMethod BuildMyGame.BuildApk %cd%/NuitrackDemo.apk -quit'
  artifacts:
    paths:
      - NuitrackDemo.apk
      - build_log.txt
    expire_in: 14d