stages:
- build_package_and_NuitrackDemo

build_unity_package:
  stage: "build_package_and_NuitrackDemo"
  tags:
    - w10vbox
  script:
    - dir
    - start deploy.sh
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
    expire_in: 14d