build_linux:
  tags:
    - windows_x64
  script:
    - mkdir build
    - '"C:\Program Files\Unity2018.3\Editor\Unity.exe" -batchmode -quit -projectPath %cd% -logFile %cd%/build_log.txt -executeMethod BuildMyGame.BuildLinux %cd%/build'
    - powershell Compress-Archive build build.zip
  artifacts:
    paths:
      - build.zip
    expire_in: 14d