stages:
- build_package_and_NuitrackDemo

build_unity_package:
  stage: "build_package_and_NuitrackDemo"
  tags:
    - w10vbox
  script:
    - dir
    - chmod +x ./deploy.cmd
    - cmd /c deploy.cmd
    - dir
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
      - log.txt
    expire_in: 14d