stages:
- build_demo_apk

build_apk:
  stage: "build_demo_apk"
  tags:
    - windows_x64
  timeout: 20 minutes
  script:
    - '"C:/Program Files/Unity2019.4/Editor/Unity.exe" -projectPath "C:/Gitlab-Runner/builds/8AhzdTYQ/0/unityapps/nuitrack-prefabs" -executeMethod BuildMyGame.BuildApk "C:/Gitlab-Runner/builds/8AhzdTYQ/0/unityapps/nuitrack-prefabs/NuitrackDemo.apk"'
  artifacts:
    paths:
      - NuitrackDemo.apk
    expire_in: 14d
    when: always