stages:
- build_package_and_NuitrackDemo

build_unity_package:
  stage: "build_package_and_NuitrackDemo"
  tags:
    - w10vbox
  script:
    - cmd /c echo %cd%
    - dir
    - dir "c:/"
    - dir "c:/Editors"
    - dir "c:/Program Files"
    - chmod +x ./deploy.cmd
    - cmd /c ./deploy.cmd
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
    expire_in: 14d