before_script:

build_unity_project:
  tags:
    - windows_x64
  script:
    - '"C:\Program Files\Unity2017.4\Editor\Unity.exe" -batchmode -quit -projectPath %cd% -exportPackage "Assets" %cd%/NuitrackSDK.unitypackage'
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
    expire_in: 14d