stages:
- build_package_and_NuitrackDemo

build_unity_package:
  stage: "build_package_and_NuitrackDemo"
  tags:
    - windows_x64
  script:
    - deploy.sh
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
      - NuitrackDemo.aab
      - NuitrackDemo.apk
      - linux_build.zip
    expire_in: 14d