stages:
- build_demo_apk

build_apk:
  stage: "build_demo_apk"
  tags:
    - windows_x64
  script:
    - '"C:\Program Files\Unity2019.4\Editor\Unity.exe" -quit -accept-apiupdate -batchmode -projectPath "${WORKSPACE}" -logFile "${WORKSPACE}/build_log.txt" -executeMethod BuildMyGame.BuildApk "${WORKSPACE}/NuitrackDemo.apk"'
  artifacts:
    paths:
      - NuitrackDemo.apk
      - build_log.txt
    expire_in: 14d