stages:
- build_package
- build_apk
- build_aab
- build_linux

build_unity_package:
  stage: "build_package"
  tags:
    - w10vbox
  script:
    - dir
    - deploy_package.cmd
    - dir
  artifacts:
    paths:
      - NuitrackSDK.unitypackage
    expire_in: 14d

build_apk:
  stage: "build_apk"
  tags:
    - w10vbox
  script:
    - dir
    - deploy_apk.cmd
    - dir
  artifacts:
    paths:
      - NuitrackDemo.apk
    expire_in: 14d

build_aab:
  stage: "build_aab"
  tags:
    - w10vbox
  script:
    - dir
    - chmod +x ./deploy_abb.cmd
    - cmd /c deploy_abb.cmd
    - dir
  artifacts:
    paths:
      - NuitrackDemo.aab
    expire_in: 14d

build_linux:
  stage: "build_linux"
  tags:
    - w10vbox
  script:
    - dir
    - chmod +x ./deploy_linux.cmd
    - cmd /c deploy_linux.cmd
    - dir
  artifacts:
    paths:
      - linux_build.zip
    expire_in: 14d