#pragma kernel Segment2Texture

RWTexture2D<float4> Result;
uniform StructuredBuffer<uint> UserIndexes : register(t1);
uniform StructuredBuffer<float4> UserColors;


int textureWidth;

[numthreads(8, 8, 1)]
void Segment2Texture(uint3 id : SV_DispatchThreadID)
{
	int rawIndex = textureWidth * id.y + id.x;
	uint userIndex = UserIndexes[rawIndex / 2];

	if(rawIndex % 2 != 0)
		Result[id.xy] = UserColors[userIndex >> 16];
	else
		Result[id.xy] = UserColors[(userIndex << 16) >> 16];
}
